# Generated by Django 5.1.7 on 2025-05-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='delivery',
            field=models.CharField(choices=[('not_needed', 'Not Needed'), ('standart', 'Standart'), ('express', 'Express')], default='not_needed', max_length=20),
        ),
    ]
